[mypy]
python_version = 3.9
strict = True
warn_unused_configs = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
no_implicit_optional = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True
